Repository ember-a11y/ember-a11y-testing, pull requests merged in 2020-08, with the labels that each got.

#183 Setup automated release system.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#199 Refactors param normalization in `a11yAudit`
  addon-test-support/audit-if.ts
  addon-test-support/audit.ts
  tests/unit/audit-test.ts
Labels: breaking

#203 Deprecate `a11yAuditIf`
  README.md
  addon-test-support/audit-if.ts
  addon-test-support/setup-global-a11y-hooks.ts
  tests/acceptance/a11y-audit-test.ts
  tests/acceptance/violations-test.ts
  tests/integration/helpers/a11y-audit-if-test.ts
  tests/integration/helpers/a11y-audit-test.ts
Labels: enhancement
