Repository ember-a11y/ember-a11y-testing, pull requests merged in 2020-09, with the labels that each got.

#205 Remove audit components in favor of industry standard tools
  README.md
  addon-test-support/audit.ts
  addon-test-support/format-violation.ts
  addon/instance-initializers/axe-component.js
  addon/instance-initializers/violations-helper.js
  addon/utils/concurrent-axe.js
  addon/utils/is-background-replaced-element.js
  addon/utils/violations-helper.ts
  app/instance-initializers/axe-component.js
  app/instance-initializers/violations-helper.js
  index.js
  package.json
  tests/acceptance/a11y-audit-test.ts
  tests/acceptance/violations-test.ts
  tests/dummy/config/environment.js
  tests/integration/instance-initializers/axe-component-test.js
  tests/unit/audit-test.ts
  tests/unit/format-violation-test.ts
  tests/unit/instance-initializers/violations-helper-test.js
  tests/unit/utils/concurrent-axe-test.js
  tests/unit/utils/is-background-replaced-element-test.js
  tests/unit/utils/violations-helper-test.js
  yarn.lock
Labels: breaking

#212 Adding ability to post violations via middleware
  .eslintrc.js
  .github/workflows/ci-build.yml
  .npmignore
  addon-test-support/index.ts
  addon-test-support/setup-middleware-reporter.ts
  index.js
  node-tests/fixtures/violations.json
  node-tests/setup-middleware-test.js
  package.json
  setup-middleware.js
  tests/acceptance/setup-middleware-reporter-test.ts
  tests/fixtures/violations.json
  types/@ember/test-helpers.d.ts
  yarn.lock
Labels: enhancement

#219 Update ember-qunit to latest beta.
  package.json
  yarn.lock
Labels: internal
