Repository ember-a11y/ember-a11y-testing, pull requests merged in 2021-12, with the labels that each got.

#331 Properly re-export types
  addon-test-support/index.ts
  addon-test-support/types/index.d.ts
Labels: bug

#326 Drop Node.js 10 support
  README.md
  package.json
Labels: breaking

#327 Delete deprecated a11yAuditIf test helper
  addon-test-support/audit-if.ts
  addon-test-support/index.ts
  addon-test-support/setup-global-a11y-hooks.ts
  tests/integration/helpers/a11y-audit-if-test.ts
Labels: breaking

#328 Update npmignore file
  .npmignore
Labels: internal

#325 Bump ember-auto-import to 2.2.4 and introduce webpack
  config/ember-try.js
  package.json
  yarn.lock
Labels: breaking

#351 Bump node-fetch to v3 and get-port to v6
  node-tests/setup-middleware-test.js
  package.json
  yarn.lock
Labels: dependencies
